<a href="https://colab.research.google.com/github/wernenveiga/fundamentos-de-ci-ncia-de-dados/blob/main/Teste_de_Hip%C3%B3tese.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Teste de Hipótese

##Bibliotecas

In [19]:
import pandas as pd
import numpy as np
from scipy import stats

In [4]:
#Arquivo

arquivo = "/content/mamalia_sleep.csv"

df_mamiferos = pd.read_csv(arquivo)

##Teste de Hipótese Z

In [7]:
med_sono_pop = df_mamiferos['sleep_total'].mean()
despd_sono_pop = df_mamiferos['sleep_total'].std()
df_mamiferos['sleep_total'].describe()

count    83.000000
mean     10.433735
std       4.450357
min       1.900000
25%       7.850000
50%      10.100000
75%      13.750000
max      19.900000
Name: sleep_total, dtype: float64

In [10]:
sono_ordem = df_mamiferos.groupby('order')['sleep_total'].mean() #Media de sonos por ordem
sono_ordem

order
Afrosoricida       15.600000
Artiodactyla        4.516667
Carnivora          10.116667
Cetacea             4.500000
Chiroptera         19.800000
Cingulata          17.750000
Didelphimorphia    18.700000
Diprotodontia      12.400000
Erinaceomorpha     10.200000
Hyracoidea          5.666667
Lagomorpha          8.400000
Monotremata         8.600000
Perissodactyla      3.466667
Pilosa             14.400000
Primates           10.500000
Proboscidea         3.600000
Rodentia           12.468182
Scandentia          8.900000
Soricomorpha       11.100000
Name: sleep_total, dtype: float64

In [14]:
is_rodentia = df_mamiferos['order'] == "Rodentia"
df_rodentia = df_mamiferos[is_rodentia]

                              name         genus   vore  ... awake  brainwt  bodywt
2                  Mountain beaver    Aplodontia  herbi  ...   9.6      NaN   1.350
7                     Vesper mouse       Calomys    NaN  ...  17.0      NaN   0.045
11                      Guinea pig         Cavis  herbi  ...  14.6  0.00550   0.728
13                      Chinchilla    Chinchilla  herbi  ...  11.5  0.00640   0.420
15       African giant pouched rat    Cricetomys   omni  ...  15.7  0.00660   1.000
26       Western american chipmunk      Eutamias  herbi  ...   9.1      NaN   0.071
38                Mongolian gerbil      Meriones  herbi  ...   9.8      NaN   0.053
39                  Golden hamster  Mesocricetus  herbi  ...   9.7  0.00100   0.120
40                           Vole       Microtus  herbi  ...  11.2      NaN   0.035
41                     House mouse           Mus  herbi  ...  11.5  0.00040   0.022
43            Round-tailed muskrat      Neofiber  herbi  ...   9.4      NaN   0.266
45                            Degu       Octodon  herbi  ...  16.3      NaN   0.210
46      Northern grasshopper mouse     Onychomys  carni  ...   9.5      NaN   0.028
56                      Deer mouse    Peromyscus    NaN  ...  12.5      NaN   0.021
63                  Laboratory rat        Rattus  herbi  ...  11.0  0.00190   0.320
64           African striped mouse     Rhabdomys   omni  ...  15.3      NaN   0.044
67                      Cotton rat      Sigmodon  herbi  ...  12.7  0.00118   0.148
68                        Mole rat        Spalax    NaN  ...  13.4  0.00300   0.122
69          Arctic ground squirrel  Spermophilus  herbi  ...   7.4  0.00570   0.920
70  Thirteen-lined ground squirrel  Spermophilus  herbi  ...  10.2  0.00400   0.101
71  Golden-mantled ground squirrel  Spermophilus  herbi  ...   8.1      NaN   0.205
75       Eastern american chipmunk        Tamias  herbi  ...   8.2      NaN   0.112

[22 rows x 11 columns]

In [16]:
sono_roedores = df_rodentia['sleep_total']
med_sono_roedores = sono_roedores.mean()

In [18]:
##Calcular o Z
z_value = (med_sono_roedores - med_sono_pop)/ despd_sono_pop
z_value

0.45714240065086326

In [22]:
stats.norm.cdf(z_value)
(1 - stats.norm.cdf(z_value))*100

32.37843478608815